ndsite/urls.py
# coding: utf-8
from django.conf.urls import patterns, include, url
from django.conf import settings
from hashlib import sha224
from datetime import date
from django.contrib import admin
from ndsite.auth_custom import ValidatingPasswordChangeForm

admin.autodiscover()

def generate_sha224():
    """
    Gera um hash para ser inserido na url do admin
    """
    today = r'%s%s%s' % (date.year, date.month, date.day)
    return r'%s' % sha224(today).hexdigest()


urlpatterns = patterns('',
    (r'^%s/' % generate_sha224(), include(admin.site.urls)),

    # Base rotes
    (r'^', include('core.urls.base', namespace='base')),
    # Letreiros
    (r'^wordnews/', include('core.urls.wordnews', namespace='wordnews')),
    # Slider da página principal
    (r'^mainslider/', include('core.urls.mainslider', namespace='mainslider')),
    # Venda direta
    (r'^directsale/', include('core.urls.directsale', namespace='directsale')),
    # Clientes
    (r'^clientes/', include('core.urls.clients', namespace='clients')),
    # Distribuidores
    (r'^distribuidores/', include('core.urls.distributor', namespace='distributor')),
    # Sobre
    (r'^about/', include('core.urls.about', namespace='about')),
    # Notícias curtas
    (r'^shortnews/', include('core.urls.shortnews', namespace='shortnews')),
    # Produtos
    (r'^services/', include('core.urls.products', namespace='products')),
    # Parceiros
    (r'^parceiros/', include('core.urls.partners', namespace='partners')),

    # Docs
    (r'^docs/', include('core.urls.docs', namespace='nd-docs')),

    # Avaliar
    url(r'^avaliar/', include('avaliar.urls', namespace='avaliar')),

    # Accounts
    url(r'^accounts/login/$', 'ndsite.auth_custom.route_login', name='login'),
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', {'template_name': 'accounts/logout.html'}, name='logout'),
    url(r'^accounts/change-password/$', 'django.contrib.auth.views.password_change', {'template_name': 'accounts/change_password.html', 'password_change_form': ValidatingPasswordChangeForm}, name='change_password'),
    url(r'^accounts/change-password/done/$', 'django.contrib.auth.views.password_change_done', {'template_name': 'accounts/change_password_done.html'}, name='change_password_done'),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^%s/(?P<path>.*)$' % settings.MEDIA_URL.strip('/'),
         'django.views.static.serve',
             {'document_root': settings.MEDIA_ROOT, 'show_indexes': False}),
    )

core/models.py
# -*- coding: utf-8 -*-
import datetime
from django.core.urlresolvers import reverse
from django.db import models
from django.template.defaultfilters import slugify
from core.choices import CHOICE_POSITION_TYPE, CHOICE_DIMENSION, CLIENT_TYPE, PARTNER_TYPE
from core.managers import MainSliderManager, WordNewsManager, DirectSaleManager, ClientManager, ProductManager, PartnerManager, AboutManager, ShortNewsManager, DistributorManager

class MainSlider(models.Model):
    """
    Slider principal
    """
    image = models.ImageField('Imagem', upload_to='main_slider')
    caption = models.CharField(u'Descrição', max_length=120, blank=True)
    html_caption = models.CharField(u'Desc. HTML', max_length=120, blank=True)
    url = models.URLField('Link', blank=True)
    active = models.BooleanField(u'Ativo', default=False)

    objects = MainSliderManager()

    class Meta:
        verbose_name = 'Slider'
        verbose_name_plural = 'Sliders'

    def __unicode__(self):
        return u'%s' % self.image

class WordNews(models.Model):
    """
    Letreiro
    """
    provider = models.CharField('Provedor', max_length=75)
    words = models.CharField('Palavras', max_length=120)
    link = models.URLField('Link')
    active = models.BooleanField(u'Ativo', default=False)

    objects = WordNewsManager()

    class Meta:
        verbose_name = 'Letreiro'
        verbose_name_plural = 'Letreiros'
        ordering = ['provider']

    def __unicode__(self):
        return u'%s' %  self.provider

class DirectSale(models.Model):
    u"""
    Venda direta de produtos da ND na página inicial.
    """
    position = models.PositiveIntegerField(u'Posição')
    position_type = models.CharField(u'Tipo de posição',
        choices=CHOICE_POSITION_TYPE, max_length=1, blank=True)
    dimension = models.CharField(u'Dimensão', max_length=5,
        choices=CHOICE_DIMENSION, blank=True)
    advertiser = models.CharField(u'Anunciante', max_length=75)
    image = models.ImageField(u'Imagem', upload_to='direct_sale')
    link = models.URLField('Link', unique=True)
    active = models.BooleanField(u'Ativo', default=False)

    objects = DirectSaleManager()

    class Meta:
        verbose_name = 'Venda direta'
        verbose_name_plural = 'Vendas direta'
        ordering = ['position']

    def save(self, *args, **kwargs):
        super(DirectSale, self).save(*args, **kwargs)

    def __unicode__(self):
        return u'%s' % self.advertiser

class Client(models.Model):
    u"""
    Clientes da ND subdividido em 4: laboratórios, clínicas, fornecedores e consultórios.
    """
    name = models.CharField(u'Nome', max_length=75)
    locality = models.CharField(u'Localidade', max_length=150, blank=True)
    image = models.ImageField(u'Logo', upload_to='clients')
    link = models.URLField('Link', blank=True)
    email = models.EmailField(u'E-mail', blank=True)
    map = models.TextField(u'Mapa', blank=True)
    phone = models.CharField(u'Fone', max_length=15, blank=True)
    client_type = models.CharField(u'Tipo de cliente', max_length='1', choices=CLIENT_TYPE)
    active = models.BooleanField(u'Ativo', default=False)

    # Campo para ordenação sem "collate"
    norm_name = models.CharField(u'Nome normalizado', max_length=75, blank=True, editable=False)

    objects = ClientManager()

    def save(self, *args, **kwargs):
        u"""
        Salva name normalizado para o norm_name

        Para fazer a migração basta ir no shell e:
        >>> from core.models import Client
        >>> clients = Client.objects.all()
        >>> for client in clients:
        ...    client.norm_name = ''.join(client.name.split('.')).lower()
        ...    client.save()
        """
        self.norm_name = ''.join(self.name.split('.')).lower()
        super(Client, self).save(*args, **kwargs)

    class Meta:
        verbose_name = 'Cliente'
        verbose_name_plural = 'Clientes'
        ordering = ['norm_name']

    def __unicode__(self):
        return u'%s' % self.name

class Distributor(models.Model):
    u"""
    Distribuidores da ND classificados por regiões.
    """
    name = models.CharField(u'Nome', max_length=75)
    address = models.CharField(u'Endereço', max_length=150, blank=True)
    city = models.CharField(u'Cidade', max_length=75)
    state = models.CharField(u'Estado', max_length=75)
    image = models.ImageField(u'Logo', upload_to='distributors')
    link = models.URLField('Link', blank=True)
    email = models.EmailField(u'E-mail', blank=True)
    map = models.TextField(u'Mapa', blank=True)
    phone = models.CharField(u'Fone', max_length=15, blank=True)
    active = models.BooleanField(u'Ativo', default=False)

    # Campo para ordenação sem "collate"
    norm_name = models.CharField(u'Nome normalizado', max_length=75, blank=True, editable=False)

    objects = DistributorManager()

    def save(self, *args, **kwargs):
        u"""
        Salva name normalizado para o norm_name

        Para fazer a migração basta ir no shell e:
        >>> from core.models import Client
        >>> clients = Client.objects.all()
        >>> for client in clients:
        ...    client.norm_name = ''.join(client.name.split('.')).lower()
        ...    client.save()
        """
        self.norm_name = ''.join(self.name.split('.')).lower()
        super(Distributor, self).save(*args, **kwargs)

    class Meta:
        verbose_name = 'Distribuidor'
        verbose_name_plural = 'Distribuidores'
        ordering = ['norm_name']

    def __unicode__(self):
        return u'%s - %s' % (self.name, self.state)

class Product(models.Model):
    u"""
    Produtos da ND.
    """
    name = models.CharField(u'Nome', max_length=75)
    slug = models.SlugField(max_length=75, blank=True)
    image = models.ImageField(u'Logo', upload_to='products')
    link = models.URLField(blank=True)
    thumb = models.ImageField(u'Thumb', upload_to='products')
    description = models.TextField(u'Descrição')
    short_description = models.TextField(u'Descrição curta')
    active = models.BooleanField(u'Ativo', default=False)
    distributors = models.ManyToManyField('Distributor', verbose_name='Distribuidores', blank=True, null=True)

    objects = ProductManager()

    class Meta:
        verbose_name = 'Produto'
        verbose_name_plural = 'Produtos'
        ordering = ['name']

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super(Product, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('base:service', kwargs={'slug': self.slug})

    def __unicode__(self):
        return u'%s' % self.name

class Partner(models.Model):
    u"""
    Parceiros da ND, subdividos em tecnologia e saúde.
    """

    name = models.CharField(u'Nome', max_length=75)
    locality = models.CharField(u'Localidade', max_length=75, blank=True)
    image = models.ImageField(u'Logo', upload_to='partner')
    description = models.TextField(u'Descrição')
    link = models.URLField('Link', blank=True)
    email = models.EmailField(u'E-mail', blank=True)
    phone = models.CharField(u'Fone', max_length=15, blank=True)
    partner_type = models.CharField(u'Tipo de parceiro', max_length='1', choices=PARTNER_TYPE)
    active = models.BooleanField(u'Ativo', default=False)

    objects = PartnerManager()

    class Meta:
        verbose_name = 'Parceiro'
        verbose_name_plural = 'Parceiros'
        ordering = ['name']

    def save(self, *args, **kwargs):
        super(Partner, self).save(*args, **kwargs)

    def __unicode__(self):
        return u'%s' % self.name

class About(models.Model):
    u"""
    Sobre a empresa.
    """

    title = models.CharField(u'Título', max_length=120)
    body = models.TextField(u'Conteúdo')
    created_date = models.DateTimeField(u'Data de criação', auto_now_add=True, editable=False)
    active = models.BooleanField(u'Ativo', default=False)

    objects = AboutManager()

    class Meta:
        verbose_name = 'Sobre'
        verbose_name_plural = 'Lista de sobre'
        ordering = ['created_date']

    def __unicode__(self):
        return  u'%s - %s' % (self.title, self.created_date)

class ShortNews(models.Model):
    u"""
    Notícia curta da página inicial.
    """

    title = models.CharField(u'Título', max_length=120, unique=True)
    slug = models.SlugField(u'Slug', editable=False, blank=True)
    author = models.CharField(u'Autor', max_length=75)
    body = models.TextField(u'Conteúdo')
    news_date = models.DateTimeField(u'Data e hora da notícia', default=datetime.datetime.now(), blank=True)
    created_date = models.DateTimeField(u'Data de criação', auto_now_add=True, editable=False)
    active = models.BooleanField(u'Ativo', default=False)

    # Managers. Ex: news = ShortNews.is_active.all()
    objects = ShortNewsManager()

    class Meta:
        verbose_name = u'Notícia curta'
        verbose_name_plural = u'Notícias curtas'
        ordering = ['-news_date']

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(ShortNews, self).save(*args, **kwargs)

    def __unicode__(self):
        return  u'%s - %s' % (self.title, self.created_date)

core/views/about.py
# -*- coding: utf-8 -*-
from django.contrib import messages
from django.contrib.auth.decorators import login_required, permission_required
from django.core.urlresolvers import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic.base import TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView
from core.forms import AboutForm
from core.models import About
from core.views.utils import generic_fields_key_value

class AboutTemplateView(TemplateView):
    template_name = 'about/business.html'

    def get_context_data(self, **kwargs):
        context = super(AboutTemplateView, self).get_context_data(**kwargs)

        about = About.objects.latest_created()
        context['about'] = about

        return context

# Sistema de gerenciamento
class AboutListView(ListView):
    model = About
    context_object_name = 'abouts'
    template_name = 'about/list.html'

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(AboutListView, self).dispatch(request, *args, **kwargs)

class AboutCreateView(CreateView):
    model = About
    form_class = AboutForm
    template_name = 'about/form.html'

    def get_success_url(self):
        messages.add_message(self.request, messages.SUCCESS, u'Sobre cadastrado com sucesso.')
        return reverse_lazy('about:list')

    def form_invalid(self, form):
        messages.add_message(self.request, messages.ERROR, u'O formulário está inválido.')
        return super(AboutCreateView, self).form_invalid(form)

    @method_decorator(permission_required('core.add_about', reverse_lazy('base:permission_denied')))
    def dispatch(self, request, *args, **kwargs):
        return super(AboutCreateView, self).dispatch(request, *args, **kwargs)

class AboutUpdateView(UpdateView):
    model = About
    form_class = AboutForm
    template_name = 'about/form.html'

    def get_success_url(self):
        messages.add_message(self.request, messages.SUCCESS, u'Sobre alterado com sucesso.')
        return reverse_lazy('about:list')

    def form_invalid(self, form):
        messages.add_message(self.request, messages.ERROR, u'O formulário está inválido.')
        return super(AboutUpdateView, self).form_invalid(form)

    @method_decorator(permission_required('core.change_about', reverse_lazy('base:permission_denied')))
    def dispatch(self, request, *args, **kwargs):
        return super(AboutUpdateView, self).dispatch(request, *args, **kwargs)

class AboutDetailView(DetailView):
    model = About
    context_object_name = 'about'
    template_name = 'base/detail.html'

    def get_context_data(self, **kwargs):
        context = super(AboutDetailView, self).get_context_data(**kwargs)

        field_keys, field_values = [], []
        generic_fields_key_value(self, field_keys, field_values)

        context['field_keys'] = field_keys
        context['field_values'] = field_values
        return context

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(AboutDetailView, self).dispatch(request, *args, **kwargs)

class AboutDeleteView(DeleteView):
    model = About
    context_object_name = 'about'
    template_name = 'base/delete.html'

    def get_success_url(self):
        messages.add_message(self.request, messages.SUCCESS, u'Sobre excluído.')
        return reverse_lazy('about:list')

    def get_context_data(self, **kwargs):
        context = super(AboutDeleteView, self).get_context_data(**kwargs)

        field_keys, field_values = [], []
        generic_fields_key_value(self, field_keys, field_values)

        context['field_keys'] = field_keys
        context['field_values'] = field_values
        return context

    @method_decorator(permission_required('core.delete_about', reverse_lazy('base:permission_denied')))
    def dispatch(self, request, *args, **kwargs):
        return super(AboutDeleteView, self).dispatch(request, *args, **kwargs)

core/views/docs.py
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.views.generic.base import TemplateView


class DocsSoftClinicRedirectView(TemplateView):
    template_name = 'docs/softclinic.html'

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(DocsSoftClinicRedirectView, self).dispatch(request, *args, **kwargs)

core/templates/snippets/by_locality.html
{% for state in new_state_list %}
    <tr class="{{ state.locality|slugify }}">
        <td style="padding: 5px 10px">
            <a href="?locality={{ state.locality }}"><img width="32" height="23" style="border: solid 1px #ddd" src="{{ STATIC_URL }}core/img/flag-{{ state.locality|slugify }}.png" alt="{{ state.locality }}" /></a>
            <a href="?locality={{ state.locality }}">
                {{ state.locality }}
            </a>
        </td>
    </tr>
{% endfor %}

core/templates/snippets/by_state.html
{% for item in state_list %}
    <tr class="{{ item.state|slugify }}">
        <td style="padding: 5px 10px">
            <a href="?state={{ item.state|slugify }}"><img width="32" height="23" style="border: solid 1px #ddd" src="{{ STATIC_URL }}core/img/flag-{{ item.state|slugify }}.png" alt="{{ item.state }}" /></a>
            <a href="?state={{ item.state|slugify }}">
                {{ item.state }}
            </a>
        </td></tr>
{% endfor %}

core/templates/snippets/clients.html
{% load core_extras %}
<style type="text/css">
    .item_3 {
        background: url("{{ STATIC_URL }}core/img/menu_bg_btn_v2.png") top center no-repeat;
        color: #777;
    }
</style>
<table class="clients_skeleton">
    <tr><td>
        <!-- Logo com/sem URL -->
        {% if client.link %}
            <a href="{{ client.link }}" target="_blank">
                <img src="{{ client.image.url }}" alt="{{ client.name }}" width="99" height="63" />
            </a>
        {% else %}
            <img src="{{ client.image.url }}" alt="{{ client.name }}" width="99" height="63" />
        {% endif %}
    </td><td>
        <strong style="font-size: 1.2em;">{{ client.name }}</strong><br />
        <!-- Com/sem localidade -->
        {% if client.locality %}
            <span class="locality">{{ client.locality }}</span>
        {% else %}
            <span class="locality">Sem localidade cadastrada</span>
        {% endif %}
        {% if client.phone %}-
            <img style="margin-top: -3px" src="{{ STATIC_URL }}core/img/phone.png" alt="Fone" width="16" height="16" />
            <span>{{ client.phone|br_phone_format }}</span>
        {% endif %}
        <div>
            <!-- Link -->
            {% if client.link %}
                <a href="{{ client.link }}" target="_blank">Site</a> -
            {% else %}
                <span class="disabled_color">Site</span> -
            {% endif %}
            <!-- Email -->
            {% if client.email %}
                <a href="mailto:{{ client.email }}">Email</a> -
            {% else %}
                <span class="disabled_color">Email</span> -
            {% endif %}
            <!-- Mapa -->
            {% if client.map %}
                <a href="{{ client.map }}" target="_blank">Mapa</a>
            {% else %}
                <span class="disabled_color">Mapa</span>
            {% endif %}
        </div>
    </td></tr>
</table>

core/templates/snippets/detail.html
<table style="margin: 10px">
    <tr>
        <td>
            <table class="detail">
            {% for k in field_keys %}
                <tr><th align="left" nowrap="nowrap">{{ k|capfirst }}</th></tr>
            {% endfor %}
            </table>
        </td>
        <td>
            <table class="detail">
            {% for v in field_values %}
                {% if v != '' %}
                    <tr><td>{{ v|safe|slice:":110"|truncatewords:"14" }}</td></tr>
                {% else %}
                    <tr><td style="color: #999; font-style: italic;">Não preenchido</td></tr>
                {% endif %}
            {% endfor %}
            </table>
        </td>
    </tr>
</table>

core/templates/snippets/distributors.html
{% load core_extras %}

<tr><td>
    <!-- Logo com/sem URL -->
    {% if client.link %}
        <a href="{{ client.link }}" target="_blank">
            <img src="{{ client.image.url }}" alt="{{ client.name }}" width="99" height="63" />
        </a>
    {% else %}
        <img src="{{ client.image.url }}" alt="{{ client.name }}" width="99" height="63" />
    {% endif %}
</td><td style="padding: 10px">
    <strong style="font-size: 1.2em;">{{ client.name }}</strong><br />
    <!-- Cidade e Estado -->
    <span class="locality">
        {% comment %}{% if client.address %}{{ client.address }} - {% endif %}{% endcomment %}
        {{ client.city }} / {{ client.state }}
        {% if client.phone %}-
            <img style="margin-top: -3px" src="{{ STATIC_URL }}core/img/phone.png" alt="Fone" width="16" height="16" />
            <span>{{ client.phone|br_phone_format }}</span>
        {% endif %}
    </span>
    <div>
        {% if client.email %}
            <a href="mailto:{{ client.email }}"><img src="{{ STATIC_URL }}core/img/email.png" alt="Email" width="26" height="14" /></a>
            <a href="mailto:{{ client.email }}">{{ client.email }}</a>
        {% endif %}
        {% comment %}
        <!-- Link -->
        {% if client.link %}
            <a href="{{ client.link }}" target="_blank">Site</a> -
        {% else %}
            <span class="disabled_color">Site</span> -
        {% endif %}
        <!-- Email -->
        {% if client.email %}
            <a href="mailto:{{ client.email }}">Email</a> -
        {% else %}
            <span class="disabled_color">Email</span> -
        {% endif %}
        <!-- Mapa -->
        {% if client.map %}
            <a href="{{ client.map }}" target="_blank">Mapa</a>
        {% else %}
            <span class="disabled_color">Mapa</span>
        {% endif %}
        {% endcomment %}
        <!-- Telefone -->
    </div>
</td><td style="width: 220px">
    {% if client.product_set.count %}
    <strong style="font-size: 11px">Distribuidor:</strong><br />
    <div>
        {% for product in client.product_set.all %}
            <a href="{{ product.get_absolute_url }}" style="text-decoration: none">
                <img src="{{ product.image.url }}" alt="{{ product.name }}" height="40" />
            </a>
        {% endfor %}
    </div>
    {% endif %}
</td></tr>

core/templates/snippets/form.html
{% for field in form %}
    {% if field.errors %}
        <tr><td>&nbsp;</td><td>{{ field.errors }}</td></tr>
    {% endif %}
    <tr>
        <td style="text-align: right; padding: 4px">{{ field.label_tag }}</td>
        <td>{{ field }}</td>
    </tr>
    {% if field.help_text %}
        <tr>
            <td>&nbsp;</td>
            <td style="font-size: 0.8em; color: #888; padding-left: 2px">{{ field.help_text }}</td>
        </tr>
    {% endif %}
{% endfor %}

core/templates/snippets/homepage.html
<script type="text/javascript">
$(function(){

    $("#usuario").focus();

    // Início de:
    // JSON Dumps para letreiro

    // hide loading
    $("span.loading_wn").hide();

    // Carregango...
    $("span.loading_wn").ajaxStart(function(){
        $(this).show();
    });
    $("span.loading_wn").ajaxStop(function(){
        $(this).hide();
    });

    // Armazenará a quantidade de news
    var count_wn = [];
    // Contador para cliques no botão, next e prev
    var count_click = {{ rand_wn }};
    // URL do JSON
    var url_wn = "{% url wordnews:json %}";

    // Carrega a 1ª news e seta count_wn
    $.ajax({
        type: "GET",
        url: url_wn,
        dataType: "json",
        success: function(response){
            $("#letreiro_wn").html(response[count_click].fields["provider"] + " - " + response[count_click].fields["words"]);
            $("#link_letreiro_wn").attr("href", response[count_click].fields["link"]);

            for (var i=0; i < response.length; i++){
                count_wn[i] = response[i];
            }

        }
    });

    // Próximo
    $("a.btn_letreiro_proximo").bind("click", function(e){

        e.preventDefault();

        // Incrementa a variável de clique
        count_click ++;

        // Se tem itens e o clique atual for menor que o nº de itens
        if (count_wn.length && count_click < count_wn.length) {

            $.ajax({
                type: "GET",
                url: url_wn,
                dataType: "json",
                success: function(response){
                    $("#letreiro_wn").html(response[count_click].fields["provider"] + " - " + response[count_click].fields["words"]);
                    $("#link_letreiro_wn").attr("href", response[count_click].fields["link"]);
                }
            });

            if (count_click == count_wn.length - 1){
                $("a.btn_letreiro_proximo").css("background", "transparent url('{{ STATIC_URL }}core/img/topo_letreiro_btn_active_skin2.png') no-repeat top left");
            } else {
                $("a.btn_letreiro_anterior").removeAttr("style");
            }

        } else { count_click = count_wn.length - 1 }

    });

    // Anterior
    $("a.btn_letreiro_anterior").bind("click", function(e){

        e.preventDefault();

        // Decrementa a variável de clique
        count_click --;

        if (count_wn.length && count_click > -1) {

            $.ajax({
                type: "GET",
                url: url_wn,
                dataType: "json",
                success: function(response){
                    $("#letreiro_wn").html(response[count_click].fields["provider"] + " - " + response[count_click].fields["words"]);
                    $("#link_letreiro_wn").attr("href", response[count_click].fields["link"]);
                }
            });

            if (count_click == 0){
                $("a.btn_letreiro_anterior").css("background", "transparent url('{{ STATIC_URL }}core/img/topo_letreiro_btn_active.png') no-repeat top left");
            } else {
                $("a.btn_letreiro_proximo").removeAttr("style");
            }

        } else { count_click = 0 }

    });

    // Nivo slider
    $('#slider').nivoSlider({
        // Specify sets like: 'fold,fade,sliceDown' or 'random'
        effect:'fade',
        pauseTime:5000,
        startSlide: {{ rand_nivo }}
    });

    // Posicionamento dos botões do slider
    var slide_btns = $('.nivo-controlNav');
    var width_slide_btns = slide_btns.width();
    slide_btns.css({'left': '50%', 'margin-left': -(width_slide_btns/2)});

    // Partners - Parceiros ao lado da logo da ND
    $('#partners').cycle({
		fx: 'fade', // choose your transition type, ex: fade, scrollUp, shuffle, etc...
        timeout: 3000,
        pause: 1,
        random: 1
	});

    // Colorbox: modal para esqueci a senha
    $(".link_esqueci_suporte").colorbox({
        width:"530px", height:"200px", iframe:true
    });

});

</script>

core/templates/snippets/message.html
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message|safe }}</li>
    {% endfor %}
</ul>
{% endif %}

core/templates/snippets/partner.html
{% load core_extras %}
<style type="text/css">
    .item_4 {
        background: url("{{ STATIC_URL }}core/img/menu_bg_btn_v2.png") top center no-repeat;
        color: #777;
    }
</style>

<table class="clients_skeleton">
    <tr><td style="border-right: dotted 1px #ddd; width: 160px;">
        {% if partner.link %}
            <a href="{{ partner.link }}" target="_blank">
                <img src="{{ partner.image.url }}" alt="{{ partner.name }}" width="160" height="95" />
            </a>
        {% else %}
            <img src="{{ partner.image.url }}" alt="{{ partner.name }}" width="160" height="95" />
        {% endif %}
    </td><td style="padding: 10px;">
        <strong>{{ partner.name }}</strong><br />
        {% if partner.locality %}
            <span class="locality">{{ partner.locality }}</span><br />
        {% else %}
            <span class="locality">Sem localidade cadastrada</span>
        {% endif %}
        <span class="description">{{ partner.description }}</span>
        <div>
            <!-- Link -->
            {% if partner.link %}
                <a href="{{ partner.link }}" target="_blank">Site</a> -
            {% else %}
                <span class="disabled_color">Site</span> -
            {% endif %}
            <!-- Email -->
            {% if partner.email %}
                <a href="mailto:{{ partner.email }}">Email</a> -
            {% else %}
                <span class="disabled_color">Email</span> -
            {% endif %}
            <!-- Telefone -->
            {% if partner.phone %}
                <span class="fone">Fone:</span> <span>{{ partner.phone|br_phone_format }}</span>
            {% else %}
                <span class="disabled_color">Fone</span>
            {% endif %}
        </div>
    </td></tr>
</table>