ndsite/urls.py
# coding: utf-8
from django.conf.urls import patterns, include, url
from django.conf import settings
from hashlib import sha224
from datetime import date
from django.contrib import admin
from ndsite.auth_custom import ValidatingPasswordChangeForm

admin.autodiscover()

def generate_sha224():
    """
    Gera um hash para ser inserido na url do admin
    """
    today = r'%s%s%s' % (date.year, date.month, date.day)
    return r'%s' % sha224(today).hexdigest()


urlpatterns = patterns('',
    (r'^%s/' % generate_sha224(), include(admin.site.urls)),

    # Base rotes
    (r'^', include('core.urls.base', namespace='base')),
    # Letreiros
    (r'^wordnews/', include('core.urls.wordnews', namespace='wordnews')),
    # Slider da página principal
    (r'^mainslider/', include('core.urls.mainslider', namespace='mainslider')),
    # Venda direta
    (r'^directsale/', include('core.urls.directsale', namespace='directsale')),
    # Clientes
    (r'^clientes/', include('core.urls.clients', namespace='clients')),
    # Distribuidores
    (r'^distribuidores/', include('core.urls.distributor', namespace='distributor')),
    # Sobre
    (r'^about/', include('core.urls.about', namespace='about')),
    # Notícias curtas
    (r'^shortnews/', include('core.urls.shortnews', namespace='shortnews')),
    # Produtos
    (r'^services/', include('core.urls.products', namespace='products')),
    # Parceiros
    (r'^parceiros/', include('core.urls.partners', namespace='partners')),

    # Docs
    (r'^docs/', include('core.urls.docs', namespace='nd-docs')),

    # Avaliar
    url(r'^avaliar/', include('avaliar.urls', namespace='avaliar')),

    # Accounts
    url(r'^accounts/login/$', 'ndsite.auth_custom.route_login', name='login'),
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', {'template_name': 'accounts/logout.html'}, name='logout'),
    url(r'^accounts/change-password/$', 'django.contrib.auth.views.password_change', {'template_name': 'accounts/change_password.html', 'password_change_form': ValidatingPasswordChangeForm}, name='change_password'),
    url(r'^accounts/change-password/done/$', 'django.contrib.auth.views.password_change_done', {'template_name': 'accounts/change_password_done.html'}, name='change_password_done'),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^%s/(?P<path>.*)$' % settings.MEDIA_URL.strip('/'),
         'django.views.static.serve',
             {'document_root': settings.MEDIA_ROOT, 'show_indexes': False}),
    )

core/models.py
# -*- coding: utf-8 -*-
import datetime
from django.core.urlresolvers import reverse
from django.db import models
from django.template.defaultfilters import slugify
from core.choices import CHOICE_POSITION_TYPE, CHOICE_DIMENSION, CLIENT_TYPE, PARTNER_TYPE
from core.managers import MainSliderManager, WordNewsManager, DirectSaleManager, ClientManager, ProductManager, PartnerManager, AboutManager, ShortNewsManager, DistributorManager

class MainSlider(models.Model):
    """
    Slider principal
    """
    image = models.ImageField('Imagem', upload_to='main_slider')
    caption = models.CharField(u'Descrição', max_length=120, blank=True)
    html_caption = models.CharField(u'Desc. HTML', max_length=120, blank=True)
    url = models.URLField('Link', blank=True)
    active = models.BooleanField(u'Ativo', default=False)

    objects = MainSliderManager()

    class Meta:
        verbose_name = 'Slider'
        verbose_name_plural = 'Sliders'

    def __unicode__(self):
        return u'%s' % self.image

class WordNews(models.Model):
    """
    Letreiro
    """
    provider = models.CharField('Provedor', max_length=75)
    words = models.CharField('Palavras', max_length=120)
    link = models.URLField('Link')
    active = models.BooleanField(u'Ativo', default=False)

    objects = WordNewsManager()

    class Meta:
        verbose_name = 'Letreiro'
        verbose_name_plural = 'Letreiros'
        ordering = ['provider']

    def __unicode__(self):
        return u'%s' %  self.provider

class DirectSale(models.Model):
    u"""
    Venda direta de produtos da ND na página inicial.
    """
    position = models.PositiveIntegerField(u'Posição')
    position_type = models.CharField(u'Tipo de posição',
        choices=CHOICE_POSITION_TYPE, max_length=1, blank=True)
    dimension = models.CharField(u'Dimensão', max_length=5,
        choices=CHOICE_DIMENSION, blank=True)
    advertiser = models.CharField(u'Anunciante', max_length=75)
    image = models.ImageField(u'Imagem', upload_to='direct_sale')
    link = models.URLField('Link', unique=True)
    active = models.BooleanField(u'Ativo', default=False)

    objects = DirectSaleManager()

    class Meta:
        verbose_name = 'Venda direta'
        verbose_name_plural = 'Vendas direta'
        ordering = ['position']

    def save(self, *args, **kwargs):
        super(DirectSale, self).save(*args, **kwargs)

    def __unicode__(self):
        return u'%s' % self.advertiser

class Client(models.Model):
    u"""
    Clientes da ND subdividido em 4: laboratórios, clínicas, fornecedores e consultórios.
    """
    name = models.CharField(u'Nome', max_length=75)
    locality = models.CharField(u'Localidade', max_length=150, blank=True)
    image = models.ImageField(u'Logo', upload_to='clients')
    link = models.URLField('Link', blank=True)
    email = models.EmailField(u'E-mail', blank=True)
    map = models.TextField(u'Mapa', blank=True)
    phone = models.CharField(u'Fone', max_length=15, blank=True)
    client_type = models.CharField(u'Tipo de cliente', max_length='1', choices=CLIENT_TYPE)
    active = models.BooleanField(u'Ativo', default=False)

    # Campo para ordenação sem "collate"
    norm_name = models.CharField(u'Nome normalizado', max_length=75, blank=True, editable=False)

    objects = ClientManager()

    def save(self, *args, **kwargs):
        u"""
        Salva name normalizado para o norm_name

        Para fazer a migração basta ir no shell e:
        >>> from core.models import Client
        >>> clients = Client.objects.all()
        >>> for client in clients:
        ...    client.norm_name = ''.join(client.name.split('.')).lower()
        ...    client.save()
        """
        self.norm_name = ''.join(self.name.split('.')).lower()
        super(Client, self).save(*args, **kwargs)

    class Meta:
        verbose_name = 'Cliente'
        verbose_name_plural = 'Clientes'
        ordering = ['norm_name']

    def __unicode__(self):
        return u'%s' % self.name

class Distributor(models.Model):
    u"""
    Distribuidores da ND classificados por regiões.
    """
    name = models.CharField(u'Nome', max_length=75)
    address = models.CharField(u'Endereço', max_length=150, blank=True)
    city = models.CharField(u'Cidade', max_length=75)
    state = models.CharField(u'Estado', max_length=75)
    image = models.ImageField(u'Logo', upload_to='distributors')
    link = models.URLField('Link', blank=True)
    email = models.EmailField(u'E-mail', blank=True)
    map = models.TextField(u'Mapa', blank=True)
    phone = models.CharField(u'Fone', max_length=15, blank=True)
    active = models.BooleanField(u'Ativo', default=False)

    # Campo para ordenação sem "collate"
    norm_name = models.CharField(u'Nome normalizado', max_length=75, blank=True, editable=False)

    objects = DistributorManager()

    def save(self, *args, **kwargs):
        u"""
        Salva name normalizado para o norm_name

        Para fazer a migração basta ir no shell e:
        >>> from core.models import Client
        >>> clients = Client.objects.all()
        >>> for client in clients:
        ...    client.norm_name = ''.join(client.name.split('.')).lower()
        ...    client.save()
        """
        self.norm_name = ''.join(self.name.split('.')).lower()
        super(Distributor, self).save(*args, **kwargs)

    class Meta:
        verbose_name = 'Distribuidor'
        verbose_name_plural = 'Distribuidores'
        ordering = ['norm_name']

    def __unicode__(self):
        return u'%s - %s' % (self.name, self.state)

class Product(models.Model):
    u"""
    Produtos da ND.
    """
    name = models.CharField(u'Nome', max_length=75)
    slug = models.SlugField(max_length=75, blank=True)
    image = models.ImageField(u'Logo', upload_to='products')
    link = models.URLField(blank=True)
    thumb = models.ImageField(u'Thumb', upload_to='products')
    description = models.TextField(u'Descrição')
    short_description = models.TextField(u'Descrição curta')
    active = models.BooleanField(u'Ativo', default=False)
    distributors = models.ManyToManyField('Distributor', verbose_name='Distribuidores', blank=True, null=True)

    objects = ProductManager()

    class Meta:
        verbose_name = 'Produto'
        verbose_name_plural = 'Produtos'
        ordering = ['name']

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super(Product, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('base:service', kwargs={'slug': self.slug})

    def __unicode__(self):
        return u'%s' % self.name

class Partner(models.Model):
    u"""
    Parceiros da ND, subdividos em tecnologia e saúde.
    """

    name = models.CharField(u'Nome', max_length=75)
    locality = models.CharField(u'Localidade', max_length=75, blank=True)
    image = models.ImageField(u'Logo', upload_to='partner')
    description = models.TextField(u'Descrição')
    link = models.URLField('Link', blank=True)
    email = models.EmailField(u'E-mail', blank=True)
    phone = models.CharField(u'Fone', max_length=15, blank=True)
    partner_type = models.CharField(u'Tipo de parceiro', max_length='1', choices=PARTNER_TYPE)
    active = models.BooleanField(u'Ativo', default=False)

    objects = PartnerManager()

    class Meta:
        verbose_name = 'Parceiro'
        verbose_name_plural = 'Parceiros'
        ordering = ['name']

    def save(self, *args, **kwargs):
        super(Partner, self).save(*args, **kwargs)

    def __unicode__(self):
        return u'%s' % self.name

class About(models.Model):
    u"""
    Sobre a empresa.
    """

    title = models.CharField(u'Título', max_length=120)
    body = models.TextField(u'Conteúdo')
    created_date = models.DateTimeField(u'Data de criação', auto_now_add=True, editable=False)
    active = models.BooleanField(u'Ativo', default=False)

    objects = AboutManager()

    class Meta:
        verbose_name = 'Sobre'
        verbose_name_plural = 'Lista de sobre'
        ordering = ['created_date']

    def __unicode__(self):
        return  u'%s - %s' % (self.title, self.created_date)

class ShortNews(models.Model):
    u"""
    Notícia curta da página inicial.
    """

    title = models.CharField(u'Título', max_length=120, unique=True)
    slug = models.SlugField(u'Slug', editable=False, blank=True)
    author = models.CharField(u'Autor', max_length=75)
    body = models.TextField(u'Conteúdo')
    news_date = models.DateTimeField(u'Data e hora da notícia', default=datetime.datetime.now(), blank=True)
    created_date = models.DateTimeField(u'Data de criação', auto_now_add=True, editable=False)
    active = models.BooleanField(u'Ativo', default=False)

    # Managers. Ex: news = ShortNews.is_active.all()
    objects = ShortNewsManager()

    class Meta:
        verbose_name = u'Notícia curta'
        verbose_name_plural = u'Notícias curtas'
        ordering = ['-news_date']

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(ShortNews, self).save(*args, **kwargs)

    def __unicode__(self):
        return  u'%s - %s' % (self.title, self.created_date)

core/views/about.py
# -*- coding: utf-8 -*-
from django.contrib import messages
from django.contrib.auth.decorators import login_required, permission_required
from django.core.urlresolvers import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic.base import TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView
from core.forms import AboutForm
from core.models import About
from core.views.utils import generic_fields_key_value

class AboutTemplateView(TemplateView):
    template_name = 'about/business.html'

    def get_context_data(self, **kwargs):
        context = super(AboutTemplateView, self).get_context_data(**kwargs)

        about = About.objects.latest_created()
        context['about'] = about

        return context

# Sistema de gerenciamento
class AboutListView(ListView):
    model = About
    context_object_name = 'abouts'
    template_name = 'about/list.html'

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(AboutListView, self).dispatch(request, *args, **kwargs)

class AboutCreateView(CreateView):
    model = About
    form_class = AboutForm
    template_name = 'about/form.html'

    def get_success_url(self):
        messages.add_message(self.request, messages.SUCCESS, u'Sobre cadastrado com sucesso.')
        return reverse_lazy('about:list')

    def form_invalid(self, form):
        messages.add_message(self.request, messages.ERROR, u'O formulário está inválido.')
        return super(AboutCreateView, self).form_invalid(form)

    @method_decorator(permission_required('core.add_about', reverse_lazy('base:permission_denied')))
    def dispatch(self, request, *args, **kwargs):
        return super(AboutCreateView, self).dispatch(request, *args, **kwargs)

class AboutUpdateView(UpdateView):
    model = About
    form_class = AboutForm
    template_name = 'about/form.html'

    def get_success_url(self):
        messages.add_message(self.request, messages.SUCCESS, u'Sobre alterado com sucesso.')
        return reverse_lazy('about:list')

    def form_invalid(self, form):
        messages.add_message(self.request, messages.ERROR, u'O formulário está inválido.')
        return super(AboutUpdateView, self).form_invalid(form)

    @method_decorator(permission_required('core.change_about', reverse_lazy('base:permission_denied')))
    def dispatch(self, request, *args, **kwargs):
        return super(AboutUpdateView, self).dispatch(request, *args, **kwargs)

class AboutDetailView(DetailView):
    model = About
    context_object_name = 'about'
    template_name = 'base/detail.html'

    def get_context_data(self, **kwargs):
        context = super(AboutDetailView, self).get_context_data(**kwargs)

        field_keys, field_values = [], []
        generic_fields_key_value(self, field_keys, field_values)

        context['field_keys'] = field_keys
        context['field_values'] = field_values
        return context

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(AboutDetailView, self).dispatch(request, *args, **kwargs)

class AboutDeleteView(DeleteView):
    model = About
    context_object_name = 'about'
    template_name = 'base/delete.html'

    def get_success_url(self):
        messages.add_message(self.request, messages.SUCCESS, u'Sobre excluído.')
        return reverse_lazy('about:list')

    def get_context_data(self, **kwargs):
        context = super(AboutDeleteView, self).get_context_data(**kwargs)

        field_keys, field_values = [], []
        generic_fields_key_value(self, field_keys, field_values)

        context['field_keys'] = field_keys
        context['field_values'] = field_values
        return context

    @method_decorator(permission_required('core.delete_about', reverse_lazy('base:permission_denied')))
    def dispatch(self, request, *args, **kwargs):
        return super(AboutDeleteView, self).dispatch(request, *args, **kwargs)

core/views/docs.py
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.views.generic.base import TemplateView


class DocsSoftClinicRedirectView(TemplateView):
    template_name = 'docs/softclinic.html'

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(DocsSoftClinicRedirectView, self).dispatch(request, *args, **kwargs)

core/templates/base/delete.html
{% extends "base/index.html" %}

{% block title %}Delete{% endblock %}
{% block header %}Deseja realmente excluir?{% endblock %}
{% block content %}
    <h2>{{ object }}</h2>
    {% include "snippets/detail.html" %}
    <form action="." method="post" style="margin: 10px;">{% csrf_token %}
        <input type="submit" value="Excluir" style="color: #CC3434; font-weight: bold;" />
        <input type="button" onclick="document.location='{% url base:manager %}'" value="Cancelar" style="font-weight: bold;" />
        <input type="button" onclick="history.back()" value="Voltar" style="font-weight: bold; color: green;" />
    </form>
{% endblock %}

core/templates/base/detail.html
{% extends "base/index.html" %}

{% block title %}Detail{% endblock %}
{% block header %}Detalhes{% endblock %}
{% block content %}
    <h2>{{ object }}</h2>
    {% include "snippets/detail.html" %}
    <div style="margin: 10px">
        <input style="font-weight: bold; color: #CC3434;" type="button" onclick="document.location='{% url base:manager %}'" value="Cancelar" />
        <input style="font-weight: bold;" type="button" onclick="history.back()" value="Voltar" />
    </div>
{% endblock %}

core/templates/base/index.html
{% load core_extras %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <title>ND Engenharia e Software - {% block title %}Manager{% endblock %}</title>
    <link rel="shortcut icon" href="{{ STATIC_URL }}favicon.ico" />
    <link rel="stylesheet" href="{{ STATIC_URL }}core/css/reset.css" />
    <link rel="stylesheet" href="{{ STATIC_URL }}core/css/text.css" />
    <link rel="stylesheet" href="{{ STATIC_URL }}core/css/960.css" />
    <link rel="stylesheet" href="{{ STATIC_URL }}core/css/default.css" />
    <link rel="stylesheet" href="{{ STATIC_URL }}core/manager/default.css" />
    <style type="text/css">
        .item_menu_hover {
            background: url("{{ STATIC_URL }}core/img/menu_bg_btn.png") center no-repeat;
            color: #777;
        }
        ul.site_drop_menu {
            background: white;
            border: solid 1px #ccc;
            position: absolute;
            margin-left: 348px;
            margin-top: 44px;
        }
        ul.site_drop_menu li {
            list-style: none;
            margin: 0;
            padding: 0;
        }
        ul.site_drop_menu li a {
            border-bottom: solid 1px #ccc;
        }
        ul.site_drop_menu li:last-child a {
            border-bottom: none;
        }
        ul.site_drop_menu li a:hover {
            background: #f5f5f5;
        }
        .item_menu_disabled {
            color: #ddd;
            cursor: default;
            border-bottom: solid 1px #ddd;
        }
        .item_menu_disabled:hover {
            color: #ccc;
            background: none;
        }
    </style>
    <script type="text/javascript" src="{{ STATIC_URL }}core/js/jquery-1.6.1.min.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}core/nivo-slider/jquery.nivo.slider.pack.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}core/js/jquery.cycle.all.latest.min.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}core/colorbox/jquery.colorbox-min.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}core/js/modernizr-2.0.min.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}core/js/respond.min.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}core/js/default.js"></script>
    <script type="text/javascript">
        $(function(){
            // Função menu drop
            $("ul.site_drop_menu").hide();
            $("a.site_drop").toggle(
                function(){
                    $(this).addClass("item_menu_hover");
                    $("ul.site_drop_menu").show();
                },
                function(){
                    $(this).removeClass("item_menu_hover");
                    $("ul.site_drop_menu").hide();
                }
            );
        });
        // Partners - Parceiros ao lado da logo da ND
        $('#partners').cycle({
            fx: 'fade', // choose your transition type, ex: fade, scrollUp, shuffle, etc...
            timeout: 15000,
            pause: 1,
            random: 1
        });
    </script>
    {% block extra_head %}
        <script type="text/javascript">
            $(function(){
                {% if user.is_authenticated %}
                    // Helper para criação de cookies
                    function createCookie(name, value, days) {
                        if (days) {
                            var date = new Date();
                            date.setTime(date.getTime() + (days * 24 * 60 * 60 * 1000));
                            var expires = "; expires=" + date.toGMTString();
                        }
                        else var expires = "";
                        document.cookie = name + "=" + value + expires + "; path=/";
                    }
                    // Helper para exclusão de cookies
                    function eraseCookie(name) {
                        createCookie(name, "", -1);
                    }
                    eraseCookie("client_address");
                    eraseCookie("counter_captcha");
                {% endif %}

                $(":text:first").focus();
            });
        </script>
    {% endblock %}
</head>
<body>
<div class="container_16">

    <br class="clear" />
    <div class="grid_10">

        <div class="grid_5" style="margin: 0"><a href="{% url base:homepage %}" class="logo_nd"><h1>ND Engenharia e Software</h1></a></div>
        <div class="grid_1 separa_logo_patrocinio" style="margin: 0">&nbsp;</div>
        <div class="grid_3" style="margin: 0" id="partners">
            {% for partner in partners %}
                <a href="{{ partner.link }}">
                    <img src="{{ partner.image.url }}"
                        alt="{{ partner.name }}"
                        title="{{ partner.name }} parceiro em {% if partner.partner_type == 'T' %}Tecnologia{% else %}Saúde{% endif %}" />
                </a>
            {% empty %}
                Não há parceiro cadastrado.
            {% endfor %}
        </div>
        <div class="clear"></div>

        <div class="grid_10 menu" style="margin: 20px 0 0 0">
            {% if user.is_authenticated %}

                {% if perms.core.add_wordnews or perms.core.change_wordnews or perms.core.delete_wordnews %}
                    <a href="{% url wordnews:list %}" class="item_menu primeiro_item_menu">Letreiros</a>
                {% else %}
                    <span class="item_menu primeiro_item_menu item_menu_disabled">Letreiros</span>
                {% endif %}

                {% if perms.core.add_mainslider or perms.core.change_mainslider or perms.core.delete_mainslider %}
                    <a href="{% url mainslider:list %}" class="item_menu">Sliders</a>
                {% else %}
                    <span class="item_menu primeiro_item_menu item_menu_disabled">Sliders</span>
                {% endif %}

                {% if perms.core.add_directsale or perms.core.change_directsale or perms.core.delete_directsale %}
                    <a href="{% url directsale:list %}" class="item_menu">V. Direta</a>
                {% else %}
                    <span class="item_menu primeiro_item_menu item_menu_disabled">V. Direta</span>
                {% endif %}

                {% if perms.core %}
                    <a href="#" class="item_menu site_drop">Site</a>
                {% else %}
                    <span class="item_menu primeiro_item_menu item_menu_disabled">Site</span>
                {% endif %}

                <a href="{% url logout %}" class="item_menu ultimo_item_menu">Sair</a>

            {% else %}
                <a href="{% url login %}" class="item_menu ultimo_item_menu">Entrar</a>
            {% endif %}

            <ul class="site_drop_menu">

                {% if perms.core.add_about or perms.core.change_about or perms.core.delete_about %}
                    <li><a href="{% url about:list %}" class="item_menu">Sobre</a></li>
                {% else %}
                    <li><span class="item_menu primeiro_item_menu item_menu_disabled">Sobre</span></li>
                {% endif %}

                {% if perms.core.add_product or perms.core.change_product or perms.core.delete_product %}
                    <li><a href="{% url products:list %}" class="item_menu">Serviços</a></li>
                {% else %}
                    <li><span class="item_menu primeiro_item_menu item_menu_disabled">Serviços</span></li>
                {% endif %}

                {% if perms.core.add_client or perms.core.change_client or perms.core.delete_client %}
                    <li><a href="{% url clients:list %}" class="item_menu">Clientes</a></li>
                {% else %}
                    <li><span class="item_menu primeiro_item_menu item_menu_disabled">Clientes</span></li>
                {% endif %}

                {% if perms.core.add_distributor or perms.core.change_distributor or perms.core.delete_distributor %}
                    <li><a href="{% url distributor:list %}" class="item_menu">Distribuidores</a></li>
                {% else %}
                    <li><span class="item_menu primeiro_item_menu item_menu_disabled">Distribuidores</span></li>
                {% endif %}

                {% if perms.core.add_partner or perms.core.change_partner or perms.core.delete_partner %}
                    <li><a href="{% url partners:list %}" class="item_menu">Parceiros</a></li>
                {% else %}
                    <li><span class="item_menu primeiro_item_menu item_menu_disabled">Parceiros</span></li>
                {% endif %}

                {% if perms.core.add_shortnews or perms.core.change_shortnews or perms.core.delete_shortnews %}
                    <li><a href="{% url shortnews:list %}" class="item_menu">Notícias</a></li>
                {% else %}
                    <li><span class="item_menu primeiro_item_menu item_menu_disabled">Notícias</span></li>
                {% endif %}

            </ul>
        
        </div>
        <div class="clear"></div>
        <div class="grid_1 sombra_esquerda">&nbsp;</div>
        <div class="grid_8 sombra_conteudo">&nbsp;</div>
        <div class="grid_1 sombra_direita">&nbsp;</div>
        <div class="clear"></div>

    </div>

    <div class="grid_6">

        <div class="grid_6 titulo_portlet_verde" style="margin: 0">
            <b>Login</b>
        </div>
        <div class="clear"></div>
        <div class="grid_6 conteudo_suporte_online" style="margin: 0; position: absolute;">
            {% block login %}
                <b style="float: left; padding: 13px 0 0 60px">
                    <span style="font-weight: normal;">Usuário:</span>&nbsp;{{ user }}<br />
                    <span style="font-weight: normal;">Nome:</span>&nbsp;{{ user.first_name }}&nbsp;{{ user.last_name }}<br />
                    <span style="font-weight: normal;">Email:</span>&nbsp;{{ user.email }}
                </b>
                <div class="toolbar_suporte">
                    <a href="{% url change_password %}" class="link_esqueci_suporte" style="float: right; margin-right: 10px">Alterar senha</a>
                </div>
            {% endblock %}
        </div>
        <div class="clear"></div>
        <div class="grid_1 sombra_esquerda sombra_altura_suporte">&nbsp;</div>
        <div class="grid_4 sombra_barra_lateral sombra_altura_suporte">&nbsp;</div>
        <div class="grid_1 sombra_direita sombra_altura_suporte">&nbsp;</div>
        <div class="clear"></div>

    </div>

    <div class="grid_16 portlet_conteudo">
        {% block content %}
            <h2>Gerenciador</h2>
            <p>
                Efetue o login para administrar as sessões do site.
                {% if user.is_superuser or user|in_group:"Avaliação" or user|in_group:"agua" %}
                    <a href="{% url admin:index %}">ND Administration</a>
                {% endif %}
            </p>
        {% endblock %}
    </div>

    <div class="clear"></div>

    <div class="grid_1 sombra_esquerda">&nbsp;</div>
    <div class="grid_14 sombra">&nbsp;</div>
    <div class="grid_1 sombra_direita">&nbsp;</div>
    <div class="clear"></div>

    <div class="grid_16 agrupador">&nbsp;</div>
    <div class="clear"></div>

    <div class="grid_16 footer">
        <address>
            <span>
                &copy; 2013 ND Engenharia e Software
            </span>
            <span style="float: right;">
                <a href="{% url base:manager %}">Gerenciador</a> |
                <a href="http://www.pulse.med.br">Pulse</a> |
                <a href="http://www.nd.com.br">ND</a>
            </span><br /><br />
            <table>
                <tr>
                    <td>São Paulo</td>
                    <td>&nbsp;&nbsp;&nbsp;</td>
                    <td>SP</td>
                    <td>&nbsp;&nbsp;&nbsp;</td>
                    <td>Brasil</td>
                    <td>&nbsp;&nbsp;&nbsp;</td>
                    <td>Centro Profissional Morumbi Shopping - Sala 314, Av. Roque Petroni Júnior, 1089 | Tel: (11) 3033.9721</td>
                </tr>
                <tr>
                    <td>Fortaleza</td>
                    <td>&nbsp;&nbsp;&nbsp;</td>
                    <td>CE</td>
                    <td>&nbsp;&nbsp;&nbsp;</td>
                    <td>Brasil</td>
                    <td>&nbsp;&nbsp;&nbsp;</td>
                    <td>Tibúrcio Cavalcante, 2594  |  Tel: (85) 3392.4342  |  Fax: (85) 3392.4342</td>
                </tr>
                <tr>
                    <td>Orlando</td>
                    <td>&nbsp;&nbsp;&nbsp;</td>
                    <td>FL</td>
                    <td>&nbsp;&nbsp;&nbsp;</td>
                    <td>USA</td>
                    <td>&nbsp;&nbsp;&nbsp;</td>
                    <td>121 S. Orange Avenue, Suite 1500 (#17), zip 32801</td>
                </tr>
            </table>
        </address>
    </div>

</div>
</body>
</html>